# Tell Travis CI we're using PHP
language: php

# Opt to use Travis container-based environment.
sudo: false

# PHP version used in first build configuration.
php:
    - "7.1"

# do test
script: php -l brBrbr-PHP7.php
